import { infoType, tableData } from "../@types/arr";

export const TableData: { [key: string]: tableData } = {
	supplier: [
		{ key: "ContactName", id: "Image", header: "", type: "img" },
		{ key: "CompanyName", id: "Company", header: "Company", type: "link", linkTo: "/supplier/", dataId: "SupplierID" },
		{ key: "ContactName", id: "ContactName", header: "Contact", type: "string" },
		{ key: "ContactTitle", id: "ContactTitle", header: "Title", type: "string" },
		{ key: "City", id: "City", header: "City", type: "string" },
		{ key: "Country", id: "Country", header: "Country", type: "string" },
	],
	products: [
		{ key: "ProductName", id: "ProductName", header: "Name", type: "link", linkTo: "/product/", dataId: "ProductID" },
		{ key: "QuantityPerUnit", id: "QuantityPerUnit", header: "Qt per unit", type: "string" },
		{ key: "UnitPrice", id: "UnitPrice", header: "Price", type: "price" },
		{ key: "UnitsInStock", id: "UnitsInStock", header: "Stock", type: "string" },
		{ key: "UnitsOnOrder", id: "UnitsOnOrder", header: "Orders", type: "string" },
	],
	orders: [
		{ key: "OrderId", id: "OrderId", header: "Id", type: "link", linkTo: "/order/", dataId: "OrderId" },
		{ key: "TotalProductsPrice", id: "TotalProductsPrice", header: "Total Price", type: "price" },
		{ key: "TotalProducts", id: "TotalProducts", header: "Products", type: "string" },
		{ key: "TotalProductsItems", id: "TotalProductsItems", header: "Quantity", type: "string" },
		{ key: "ShippedDate", safetyKey: "OrderDate", id: "ShippedDate", header: "Shipped", type: "date" },
		{ key: "ShipName", id: "ShipName", header: "Ship Name", type: "string" },
		{ key: "ShipCity", id: "ShipCity", header: "City", type: "string" },
		{ key: "ShipCountry", id: "ShipCountry", header: "Country", type: "string" },
	],
	order: [
		{
			key: "ProductName",
			id: "ProductName",
			header: "Product",
			type: "link",
			linkTo: "/product/",
			dataId: "ProductID",
		},
		{ key: "Quantity", id: "Quantity", header: "Quantity", type: "string" },
		{ key: "OrderUnitPrice", id: "OrderUnitPrice", header: "Order Price", type: "price" },
		{ key: "Quantity", id: "MultiplyQuantity", header: "Total Price", type: "price", multiply: "OrderUnitPrice" },
		{ key: "Discount", id: "Discount", header: "Discount", type: "string" },
	],
	employes: [
		{ key: ["FirstName", "LastName"], id: "Image", header: "", type: "img" },
		{
			key: ["FirstName", "LastName"],
			id: "Name",
			header: "Name",
			type: "link",
			linkTo: "/employee/",
			dataId: "EmployeeID",
		},
		{ key: "Title", id: "Title", header: "Title", type: "string" },
		{ key: "City", id: "City", header: "City", type: "string" },
		{ key: "HomePhone", id: "HomePhone", header: "Phone", type: "string" },
		{ key: "Country", id: "Country", header: "Country", type: "string" },
	],
	customers: [
		{ key: "ContactName", id: "Image", header: "", type: "img" },
		{
			key: "CompanyName",
			id: "CompanyName",
			header: "Company",
			type: "link",
			linkTo: "/customer/",
			dataId: "CustomerID",
		},
		{ key: "ContactName", id: "ContactName", header: "Contact", type: "string" },
		{ key: "ContactTitle", id: "ContactTitle", header: "Title", type: "string" },
		{ key: "City", id: "City", header: "City", type: "string" },
		{ key: "Country", id: "Country", header: "Country", type: "string" },
	],
};

export const IndividualData: { [key: string]: infoType } = {
	supplier: [
		{ key: "CompanyName", title: "Company Name", type: "string" },
		{ key: "Region", title: "Region", type: "string" },
		{ key: "ContactName", title: "Contact Name", type: "string" },
		{ key: "PostalCode", title: "Postal Code", type: "string" },
		{ key: "ContactTitle", title: "Contact Title", type: "string" },
		{ key: "Country", title: "Country", type: "string" },
		{ key: "Address", title: "Address", type: "string" },
		{ key: "Phone", title: "Phone", type: "string" },
		{ key: "City", title: "City", type: "string" },
	],
	product: [
		{ key: "ProductName", title: "Product Name", type: "string" },
		{ key: "UnitsInStock", title: "Units In Stock", type: "string" },
		{ key: "SupplierName", title: "Supplier", type: "link", linkTo: "/supplier/", dataId: "SupplierID" },
		{ key: "UnitsOnOrder", title: "Units In Order", type: "string" },
		{ key: "QuantityPerUnit", title: "Quantity Per Unit", type: "string" },
		{ key: "ReorderLevel", title: "Reorder Level", type: "string" },
		{ key: "UnitPrice", title: "Unit Price", type: "price" },
		{ key: "Discontinued", title: "Discontinued", type: "string" },
	],
	order: [
		{ key: "CustomerID", title: "Customer ID", type: "link", linkTo: "/customer/", dataId: "CustomerID" },
		{ key: "OrderDate", title: "Order Date", type: "date" },
		{ key: "ShipName", title: "Ship Name", type: "string" },
		{ key: "RequiredDate", title: "Required Date", type: "date" },
		{ key: "TotalProducts", title: "Total Products", type: "string" },
		{ key: "ShippedDate", title: "Shipped Date", type: "date" },
		{ key: "TotalProductsItems", title: "Total Products Items", type: "string" },
		{ key: "ShipCity", title: "Ship City", type: "string" },
		{ key: "TotalProductsPrice", title: "Total Products Price", type: "price" },
		{ key: "ShipRegion", title: "Ship Region", type: "string" },
		{ key: "TotalProductsDiscount", title: "Total Products Discount", type: "price" },
		{ key: "ShipPostalCode", title: "Ship Postal Code", type: "string" },
		{ key: "ShipVia", title: "Ship Via", type: "string" },
		{ key: "ShipCountry", title: "Ship Country", type: "string" },
		{ key: "Freight", title: "Freight", type: "price" },
	],
	employee: [
		{ key: ["FirstName", "LastName"], title: "Name", type: "string" },
		{ key: "PostalCode", title: "Postal Code", type: "string" },
		{ key: "Title", title: "Title", type: "string" },
		{ key: "Country", title: "Country", type: "string" },
		{ key: "TitleOfCourtesy", title: "Title Of Courtesy", type: "string" },
		{ key: "HomePhone", title: "Home Phone", type: "string" },
		{ key: "BirthDate", title: "Birth Date", type: "string" },
		{ key: "Extension", title: "Extension", type: "string" },
		{ key: "HireDate", title: "Hire Date", type: "string" },
		{ key: "Notes", title: "Notes", type: "string" },
		{ key: "Address", title: "Address", type: "string" },
		{
			key: ["ReportFirstName", "ReportLastName"],
			title: "Reports To",
			type: "link",
			linkTo: "/employee/",
			dataId: "ReportId",
		},
		{ key: "City", title: "City", type: "string" },
	],
	customer: [
		{ key: "CompanyName", title: "Company Name", type: "string" },
		{ key: "PostalCode", title: "Postal Code", type: "string" },
		{ key: "ContactName", title: "Contact Name", type: "string" },
		{ key: "Region", title: "Region", type: "string" },
		{ key: "ContactTitle", title: "Contact Title", type: "string" },
		{ key: "Country", title: "Country", type: "string" },
		{ key: "Address", title: "Address", type: "string" },
		{ key: "Phone", title: "Phone", type: "string" },
		{ key: "City", title: "City", type: "string" },
		{ key: "Fax", title: "Fax", type: "string" },
	],
};
