import { arrType } from "../@types/arr";

export const IndividualData: { [key: string]: arrType } = {
	supplier: [
		{ key: "CompanyName", title: "Company Name", type: "string" },
		{ key: "Region", title: "Region", type: "string" },
		{ key: "ContactName", title: "Contact Name", type: "string" },
		{ key: "PostalCode", title: "Postal Code", type: "string" },
		{ key: "ContactTitle", title: "Contact Title", type: "string" },
		{ key: "Country", title: "Country", type: "string" },
		{ key: "Address", title: "Address", type: "string" },
		{ key: "Phone", title: "Phone", type: "string" },
		{ key: "City", title: "City", type: "string" },
	],
	product: [
		{ key: "ProductName", title: "Product Name", type: "string" },
		{ key: "UnitsInStock", title: "Units In Stock", type: "string" },
		{ key: "SupplierName", title: "Supplier", type: "link", linkTo: "/supplier/", dataId: "SupplierID" },
		{ key: "UnitsOnOrder", title: "Units In Order", type: "string" },
		{ key: "QuantityPerUnit", title: "Quantity Per Unit", type: "string" },
		{ key: "ReorderLevel", title: "Reorder Level", type: "string" },
		{ key: "UnitPrice", title: "Unit Price", type: "price" },
		{ key: "Discontinued", title: "Discontinued", type: "string" },
	],
	order: [
		{ key: "CustomerID", title: "Customer ID", type: "link", linkTo: "/customer/", dataId: "CustomerID" },
		{ key: "OrderDate", title: "Order Date", type: "date" },
		{ key: "ShipName", title: "Ship Name", type: "string" },
		{ key: "RequiredDate", title: "Required Date", type: "date" },
		{ key: "TotalProducts", title: "Total Products", type: "string" },
		{ key: "ShippedDate", title: "Shipped Date", type: "date" },
		{ key: "TotalProductsItems", title: "Total Products Items", type: "string" },
		{ key: "ShipCity", title: "Ship City", type: "string" },
		{ key: "TotalProductsPrice", title: "Total Products Price", type: "price" },
		{ key: "ShipRegion", title: "Ship Region", type: "string" },
		{ key: "TotalProductsDiscount", title: "Total Products Discount", type: "price" },
		{ key: "ShipPostalCode", title: "Ship Postal Code", type: "string" },
		{ key: "ShipVia", title: "Ship Via", type: "string" },
		{ key: "ShipCountry", title: "Ship Country", type: "string" },
		{ key: "Freight", title: "Freight", type: "price" },
	],
	employee: [
		{ key: ["FirstName", "LastName"], title: "Name", type: "string" },
		{ key: "PostalCode", title: "Postal Code", type: "string" },
		{ key: "Title", title: "Title", type: "string" },
		{ key: "Country", title: "Country", type: "string" },
		{ key: "TitleOfCourtesy", title: "Title Of Courtesy", type: "string" },
		{ key: "HomePhone", title: "Home Phone", type: "string" },
		{ key: "BirthDate", title: "Birth Date", type: "string" },
		{ key: "Extension", title: "Extension", type: "string" },
		{ key: "HireDate", title: "Hire Date", type: "string" },
		{ key: "Notes", title: "Notes", type: "string" },
		{ key: "Address", title: "Address", type: "string" },
		{
			key: ["ReportFirstName", "ReportLastName"],
			title: "Reports To",
			type: "link",
			linkTo: "/employee/",
			dataId: "ReportId",
		},
		{ key: "City", title: "City", type: "string" },
	],
	customer: [
		{ key: "CompanyName", title: "Company Name", type: "string" },
		{ key: "PostalCode", title: "Postal Code", type: "string" },
		{ key: "ContactName", title: "Contact Name", type: "string" },
		{ key: "Region", title: "Region", type: "string" },
		{ key: "ContactTitle", title: "Contact Title", type: "string" },
		{ key: "Country", title: "Country", type: "string" },
		{ key: "Address", title: "Address", type: "string" },
		{ key: "Phone", title: "Phone", type: "string" },
		{ key: "City", title: "City", type: "string" },
		{ key: "Fax", title: "Fax", type: "string" },
	],
};
